source "https://rubygems.org"

# "gem list" to query local install

gem "roda"
gem "puma"
### Tilt allows rendering in several engines
gem "tilt"
### erubis is an implementation of erb
### it also can be compiled, per https://github.com/rtomayko/tilt
# Erubis is at 2.7.0 / # erb itself is at 2.2.0 as of Dec 2021
gem "erubis"
### gem "slim"
# gem "sassc"
gem 'rack-unreloader' 
# gem 'pg'
# gem 'sequel'